// ReSharper disable InconsistentNaming

// ReSharper disable UnusedMember.Local

using System.Collections.Frozen;
using KC = InputHooks.KeyCode;

namespace WaylandInput;

internal static class KeycodeMap
{
    public static readonly IReadOnlyDictionary<KC, LinuxKC[]> ToLinux;
    public static readonly IReadOnlyDictionary<LinuxKC, KC[]> ToKeyCode;

    static KeycodeMap()
    {
        (KC Standard, LinuxKC Linux)[] keycodeToLinuxKey =
        [
            (KC.Undefined, LinuxKC.KEY_RESERVED),
            (KC.Escape, LinuxKC.KEY_ESC),
            (KC.Backspace, LinuxKC.KEY_BACKSPACE),
            (KC.Enter, LinuxKC.KEY_ENTER),
            (KC.LeftShift, LinuxKC.KEY_LEFTSHIFT),
            (KC.LeftControl, LinuxKC.KEY_LEFTCTRL),
            (KC.LeftAlt, LinuxKC.KEY_LEFTALT),
            (KC.LeftMeta, LinuxKC.KEY_LEFTMETA),
            (KC.RightShift, LinuxKC.KEY_RIGHTSHIFT),
            (KC.RightControl, LinuxKC.KEY_RIGHTCTRL),
            (KC.RightAlt, LinuxKC.KEY_RIGHTALT),
            (KC.RightMeta, LinuxKC.KEY_RIGHTMETA),
            (KC.Vc102, LinuxKC.KEY_102ND),
            (KC.Space, LinuxKC.KEY_SPACE),
            (KC.PageUp, LinuxKC.KEY_PAGEUP),
            (KC.PageDown, LinuxKC.KEY_PAGEDOWN),
            (KC.End, LinuxKC.KEY_END),
            (KC.Home, LinuxKC.KEY_HOME),
            (KC.Left, LinuxKC.KEY_LEFT),
            (KC.Up, LinuxKC.KEY_UP),
            (KC.Right, LinuxKC.KEY_RIGHT),
            (KC.Down, LinuxKC.KEY_DOWN),
            (KC.Insert, LinuxKC.KEY_INSERT),
            (KC.Delete, LinuxKC.KEY_DELETE),
            (KC.PrintScreen, LinuxKC.KEY_PRINT),
            (KC.ScrollLock, LinuxKC.KEY_SCROLLLOCK),
            (KC.Pause, LinuxKC.KEY_PAUSE),
            (KC.F1, LinuxKC.KEY_F1),
            (KC.F2, LinuxKC.KEY_F2),
            (KC.F3, LinuxKC.KEY_F3),
            (KC.F4, LinuxKC.KEY_F4),
            (KC.F5, LinuxKC.KEY_F5),
            (KC.F6, LinuxKC.KEY_F6),
            (KC.F7, LinuxKC.KEY_F7),
            (KC.F8, LinuxKC.KEY_F8),
            (KC.F9, LinuxKC.KEY_F9),
            (KC.F10, LinuxKC.KEY_F10),
            (KC.F11, LinuxKC.KEY_F11),
            (KC.F12, LinuxKC.KEY_F12),
            (KC.F13, LinuxKC.KEY_F13),
            (KC.F14, LinuxKC.KEY_F14),
            (KC.F15, LinuxKC.KEY_F15),
            (KC.F16, LinuxKC.KEY_F16),
            (KC.F17, LinuxKC.KEY_F17),
            (KC.F18, LinuxKC.KEY_F18),
            (KC.F19, LinuxKC.KEY_F19),
            (KC.F20, LinuxKC.KEY_F20),
            (KC.F21, LinuxKC.KEY_F21),
            (KC.F22, LinuxKC.KEY_F22),
            (KC.F23, LinuxKC.KEY_F23),
            (KC.F24, LinuxKC.KEY_F24),
            (KC.N1, LinuxKC.KEY_1),
            (KC.N2, LinuxKC.KEY_2),
            (KC.N3, LinuxKC.KEY_3),
            (KC.N4, LinuxKC.KEY_4),
            (KC.N5, LinuxKC.KEY_5),
            (KC.N6, LinuxKC.KEY_6),
            (KC.N7, LinuxKC.KEY_7),
            (KC.N8, LinuxKC.KEY_8),
            (KC.N9, LinuxKC.KEY_9),
            (KC.N0, LinuxKC.KEY_0),
            (KC.Minus, LinuxKC.KEY_MINUS),
            (KC.Equals, LinuxKC.KEY_EQUAL),
            (KC.Tab, LinuxKC.KEY_TAB),
            (KC.Q, LinuxKC.KEY_Q),
            (KC.W, LinuxKC.KEY_W),
            (KC.E, LinuxKC.KEY_E),
            (KC.R, LinuxKC.KEY_R),
            (KC.T, LinuxKC.KEY_T),
            (KC.Y, LinuxKC.KEY_Y),
            (KC.U, LinuxKC.KEY_U),
            (KC.I, LinuxKC.KEY_I),
            (KC.O, LinuxKC.KEY_O),
            (KC.P, LinuxKC.KEY_P),
            (KC.OpenBracket, LinuxKC.KEY_LEFTBRACE),
            (KC.CloseBracket, LinuxKC.KEY_RIGHTBRACE),
            (KC.Enter, LinuxKC.KEY_ENTER),
            (KC.LeftControl, LinuxKC.KEY_LEFTCTRL),
            (KC.A, LinuxKC.KEY_A),
            (KC.S, LinuxKC.KEY_S),
            (KC.D, LinuxKC.KEY_D),
            (KC.F, LinuxKC.KEY_F),
            (KC.G, LinuxKC.KEY_G),
            (KC.H, LinuxKC.KEY_H),
            (KC.J, LinuxKC.KEY_J),
            (KC.K, LinuxKC.KEY_K),
            (KC.L, LinuxKC.KEY_L),
            (KC.Semicolon, LinuxKC.KEY_SEMICOLON),
            (KC.Quote, LinuxKC.KEY_APOSTROPHE),
            (KC.BackQuote, LinuxKC.KEY_GRAVE),
            (KC.Z, LinuxKC.KEY_Z),
            (KC.X, LinuxKC.KEY_X),
            (KC.C, LinuxKC.KEY_C),
            (KC.V, LinuxKC.KEY_V),
            (KC.B, LinuxKC.KEY_B),
            (KC.N, LinuxKC.KEY_N),
            (KC.M, LinuxKC.KEY_M),
            (KC.Comma, LinuxKC.KEY_COMMA),
            (KC.Period, LinuxKC.KEY_DOT),
            (KC.Slash, LinuxKC.KEY_SLASH),
            (KC.NumPad0, LinuxKC.KEY_KP0),
            (KC.NumPad1, LinuxKC.KEY_KP1),
            (KC.NumPad2, LinuxKC.KEY_KP2),
            (KC.NumPad3, LinuxKC.KEY_KP3),
            (KC.NumPad4, LinuxKC.KEY_KP4),
            (KC.NumPad5, LinuxKC.KEY_KP5),
            (KC.NumPad6, LinuxKC.KEY_KP6),
            (KC.NumPad7, LinuxKC.KEY_KP7),
            (KC.NumPad8, LinuxKC.KEY_KP8),
            (KC.NumPad9, LinuxKC.KEY_KP9),
            (KC.NumPadAsterisk, LinuxKC.KEY_KPASTERISK),
            (KC.NumPadPlus, LinuxKC.KEY_KPPLUS),
            (KC.NumPadMinus, LinuxKC.KEY_KPMINUS),
            (KC.NumPadPeriod, LinuxKC.KEY_KPDOT),
            (KC.NumPadForwardSlash, LinuxKC.KEY_KPSLASH),
            (KC.NumPadEnter, LinuxKC.KEY_KPENTER),
            (KC.CapsLock, LinuxKC.KEY_CAPSLOCK),
            (KC.NumLock, LinuxKC.KEY_NUMLOCK),
            (KC.NumPadEquals, LinuxKC.KEY_KPEQUAL),
            (KC.Backslash, LinuxKC.KEY_BACKSLASH),
            (KC.JpComma, LinuxKC.KEY_KPJPCOMMA),
            (KC.App1, LinuxKC.KEY_PROG1),
            (KC.App2, LinuxKC.KEY_PROG2),
            (KC.App3, LinuxKC.KEY_PROG3),
            (KC.App4, LinuxKC.KEY_PROG4),
            (KC.AppCalculator, LinuxKC.KEY_CALC),
            (KC.AppBrowser, LinuxKC.KEY_WWW),
            (KC.AppMail, LinuxKC.KEY_MAIL),
            (KC.BrowserBack, LinuxKC.KEY_BACK),
            (KC.BrowserForward, LinuxKC.KEY_FORWARD),
            (KC.BrowserRefresh, LinuxKC.KEY_REFRESH),
            (KC.BrowserStop, LinuxKC.KEY_STOP),
            (KC.BrowserSearch, LinuxKC.KEY_SEARCH),
            (KC.BrowserFavorites, LinuxKC.KEY_FAVORITES),
            (KC.BrowserHome, LinuxKC.KEY_HOMEPAGE),
            
            (KC.MediaPlay, LinuxKC.KEY_PLAY),
            (KC.MediaStop, LinuxKC.KEY_STOP),
            (KC.MediaNext, LinuxKC.KEY_NEXTSONG),
            (KC.MediaPrevious, LinuxKC.KEY_PREVIOUSSONG),
            (KC.MediaEject, LinuxKC.KEY_EJECTCD),
            (KC.MediaSelect, LinuxKC.KEY_SELECT),
            (KC.VolumeDown, LinuxKC.KEY_VOLUMEDOWN),
            (KC.VolumeUp, LinuxKC.KEY_VOLUMEUP),
            (KC.Help, LinuxKC.KEY_HELP),
            (KC.Hangul, LinuxKC.KEY_HANGUEL),
            (KC.Hanja, LinuxKC.KEY_HANJA),
            (KC.ContextMenu, LinuxKC.KEY_CONTEXT_MENU),
            (KC.Power, LinuxKC.KEY_POWER),
            (KC.Sleep, LinuxKC.KEY_SLEEP),
            (KC.NumPadSeparator, LinuxKC.KEY_KPCOMMA),
            (KC.PrintScreen, LinuxKC.KEY_PRINT),
            (KC.Pause, LinuxKC.KEY_PAUSE),
            (KC.Accept, LinuxKC.KEY_KBDINPUTASSIST_ACCEPT),
            (KC.Cancel, LinuxKC.KEY_KBDINPUTASSIST_CANCEL),
            (KC.NumPadClear, LinuxKC.KEY_CLEAR),
            (KC.Yen, LinuxKC.KEY_YEN),
            (KC.ImeOff, LinuxKC.KEY_KEYBOARD),
            (KC.ImeOn, LinuxKC.KEY_ONSCREEN_KEYBOARD),
            (KC.Hiragana, LinuxKC.KEY_HIRAGANA),
            (KC.Katakana, LinuxKC.KEY_KATAKANA),
            (KC.ModeChange, LinuxKC.KEY_MODE),
            (KC.KatakanaHiragana, LinuxKC.KEY_KATAKANAHIRAGANA),
            (KC.Convert, LinuxKC.KEY_HENKAN),
            (KC.NonConvert, LinuxKC.KEY_MUHENKAN),
            (KC.Junja, LinuxKC.KEY_ZENKAKUHANKAKU),
            (KC.Process, LinuxKC.KEY_PROGRAM),
            (KC.Function, LinuxKC.KEY_FN),
            (KC.VendorKey, LinuxKC.KEY_VENDOR),
            (KC.Final, LinuxKC.KEY_KBDINPUTASSIST_NEXTGROUP),
            (KC.AlphaNumeric, LinuxKC.KEY_KBD_LAYOUT_NEXT),
            (KC.VolumeMute, LinuxKC.KEY_MUTE),
            (KC.MouseLeft, LinuxKC.BTN_LEFT),
            (KC.MouseRight, LinuxKC.BTN_RIGHT),
            (KC.MouseMiddle, LinuxKC.BTN_MIDDLE),
            (KC.MouseBack, LinuxKC.BTN_BACK),
            (KC.MouseForward, LinuxKC.BTN_FORWARD),
            (KC.MouseTask, LinuxKC.BTN_TASK),
            
            
            /*
            (KC.VcKanji, LinuxKC.KEY_ONSCREEN_KEYBOARD), // duplicate of ImeOn
            (KC.VcKana, LinuxKC.KEY_UNKNOWN), // ???
            (KC.VcUnderscore, LinuxKC.KEY_UNKNOWN),
            */
        ];

#if DEBUG
        // log all of the missing keys to the console
        var missingKeys = Enum.GetValues<KC>().Where(x => keycodeToLinuxKey.All(y => y.Standard != x)).ToArray();

        if (missingKeys.Length > 0)
        {
            foreach(var missing in missingKeys)
            {
                Console.WriteLine($"Missing key mapping for: {missing} ({(int)missing})");
            }
        }
        else
        {
            Console.WriteLine("All key mappings are present.");
        }

#endif

        ToLinux = keycodeToLinuxKey
            .GroupBy(x => x.Standard)
            .ToDictionary(x => x.Key, x => x.Select(y => y.Linux).ToArray())
            .ToFrozenDictionary();

        ToKeyCode = keycodeToLinuxKey
            .GroupBy(x => x.Linux)
            .ToDictionary(x => x.Key, x => x.Select(y => y.Standard).ToArray())
            .ToFrozenDictionary();
    }

    /// <summary>
    /// Reads the /usr/include/linux/input-event-codes.h file, and prints out the constants
    /// todo: Would be better as a source generator, but this is a quick tool to fill out the constants we need
    /// </summary>
    // ReSharper disable once UnusedMember.Global
    public static void Parse()
    {
        var file = File.ReadAllText("/usr/include/linux/input-event-codes.h");
        // parse each line, and print the related "const" to each
        var kvp = file.Split('\n')
            .Select(x => x.Trim())
            .Where(x => x.StartsWith("#define") && x.Contains("KEY_"))
            .Select(x =>
            {
                //Console.WriteLine($"First step: {x}");
                // remove #define 
                const string defineStr = "#define ";
                var defineIdx = x.IndexOf(defineStr, StringComparison.Ordinal);
                return x.Substring(defineIdx + defineStr.Length);
            })
            .Select(x =>
            {
                // remove any block comments
                var commentIdx = x.IndexOf("/*", StringComparison.Ordinal);
                if (commentIdx >= 0)
                {
                    x = x[..commentIdx];
                }

                var split = x.Split(' ', StringSplitOptions.RemoveEmptyEntries);
                if (split.Length < 2)
                    split = x.Split('\t', StringSplitOptions.RemoveEmptyEntries);

                for (int i = 0; i < split.Length; i++)
                {
                    split[i] = split[i].Replace(" ", "").Replace("\t", "").Replace("\n", "");
                }

                if (split.Length > 2)
                {
                    //Console.WriteLine($"Errant value: '{string.Join('|', split)}'");
                    split = [split[0], split[1]];
                }

                //Console.WriteLine($"Second step: '{x}' => '{string.Join('|', split)}'");

                return split;
            })
            .Select<string[], (string Text, string Value)>(x => (Text: x[0], Value: x[1]));

        Console.WriteLine("private enum LinuxKeyCodes : ushort");
        Console.WriteLine("{");

        foreach (var kvpLine in kvp)
        {
            Console.WriteLine($"\t{kvpLine.Text} = {kvpLine.Value},");
        }

        Console.WriteLine("}");
        Console.WriteLine();
    }

    // constants based on /usr/include/linux/input-event/codes.h
}

internal enum LinuxKC : ushort
{
    KEY_RESERVED = 0,
    KEY_ESC = 1,
    KEY_1 = 2,
    KEY_2 = 3,
    KEY_3 = 4,
    KEY_4 = 5,
    KEY_5 = 6,
    KEY_6 = 7,
    KEY_7 = 8,
    KEY_8 = 9,
    KEY_9 = 10,
    KEY_0 = 11,
    KEY_MINUS = 12,
    KEY_EQUAL = 13,
    KEY_BACKSPACE = 14,
    KEY_TAB = 15,
    KEY_Q = 16,
    KEY_W = 17,
    KEY_E = 18,
    KEY_R = 19,
    KEY_T = 20,
    KEY_Y = 21,
    KEY_U = 22,
    KEY_I = 23,
    KEY_O = 24,
    KEY_P = 25,
    KEY_LEFTBRACE = 26,
    KEY_RIGHTBRACE = 27,
    KEY_ENTER = 28,
    KEY_LEFTCTRL = 29,
    KEY_A = 30,
    KEY_S = 31,
    KEY_D = 32,
    KEY_F = 33,
    KEY_G = 34,
    KEY_H = 35,
    KEY_J = 36,
    KEY_K = 37,
    KEY_L = 38,
    KEY_SEMICOLON = 39,
    KEY_APOSTROPHE = 40,
    KEY_GRAVE = 41,
    KEY_LEFTSHIFT = 42,
    KEY_BACKSLASH = 43,
    KEY_Z = 44,
    KEY_X = 45,
    KEY_C = 46,
    KEY_V = 47,
    KEY_B = 48,
    KEY_N = 49,
    KEY_M = 50,
    KEY_COMMA = 51,
    KEY_DOT = 52,
    KEY_SLASH = 53,
    KEY_RIGHTSHIFT = 54,
    KEY_KPASTERISK = 55,
    KEY_LEFTALT = 56,
    KEY_SPACE = 57,
    KEY_CAPSLOCK = 58,
    KEY_F1 = 59,
    KEY_F2 = 60,
    KEY_F3 = 61,
    KEY_F4 = 62,
    KEY_F5 = 63,
    KEY_F6 = 64,
    KEY_F7 = 65,
    KEY_F8 = 66,
    KEY_F9 = 67,
    KEY_F10 = 68,
    KEY_NUMLOCK = 69,
    KEY_SCROLLLOCK = 70,
    KEY_KP7 = 71,
    KEY_KP8 = 72,
    KEY_KP9 = 73,
    KEY_KPMINUS = 74,
    KEY_KP4 = 75,
    KEY_KP5 = 76,
    KEY_KP6 = 77,
    KEY_KPPLUS = 78,
    KEY_KP1 = 79,
    KEY_KP2 = 80,
    KEY_KP3 = 81,
    KEY_KP0 = 82,
    KEY_KPDOT = 83,
    KEY_ZENKAKUHANKAKU = 85,
    KEY_102ND = 86,
    KEY_F11 = 87,
    KEY_F12 = 88,
    KEY_RO = 89,
    KEY_KATAKANA = 90,
    KEY_HIRAGANA = 91,
    KEY_HENKAN = 92,
    KEY_KATAKANAHIRAGANA = 93,
    KEY_MUHENKAN = 94,
    KEY_KPJPCOMMA = 95,
    KEY_KPENTER = 96,
    KEY_RIGHTCTRL = 97,
    KEY_KPSLASH = 98,
    KEY_SYSRQ = 99,
    KEY_RIGHTALT = 100,
    KEY_LINEFEED = 101,
    KEY_HOME = 102,
    KEY_UP = 103,
    KEY_PAGEUP = 104,
    KEY_LEFT = 105,
    KEY_RIGHT = 106,
    KEY_END = 107,
    KEY_DOWN = 108,
    KEY_PAGEDOWN = 109,
    KEY_INSERT = 110,
    KEY_DELETE = 111,
    KEY_MACRO = 112,
    KEY_MUTE = 113,
    KEY_VOLUMEDOWN = 114,
    KEY_VOLUMEUP = 115,
    KEY_POWER = 116,
    KEY_KPEQUAL = 117,
    KEY_KPPLUSMINUS = 118,
    KEY_PAUSE = 119,
    KEY_SCALE = 120,
    KEY_KPCOMMA = 121,
    KEY_HANGEUL = 122,
    KEY_HANGUEL = KEY_HANGEUL,
    KEY_HANJA = 123,
    KEY_YEN = 124,
    KEY_LEFTMETA = 125,
    KEY_RIGHTMETA = 126,
    KEY_COMPOSE = 127,
    KEY_STOP = 128,
    KEY_AGAIN = 129,
    KEY_PROPS = 130,
    KEY_UNDO = 131,
    KEY_FRONT = 132,
    KEY_COPY = 133,
    KEY_OPEN = 134,
    KEY_PASTE = 135,
    KEY_FIND = 136,
    KEY_CUT = 137,
    KEY_HELP = 138,
    KEY_MENU = 139,
    KEY_CALC = 140,
    KEY_SETUP = 141,
    KEY_SLEEP = 142,
    KEY_WAKEUP = 143,
    KEY_FILE = 144,
    KEY_SENDFILE = 145,
    KEY_DELETEFILE = 146,
    KEY_XFER = 147,
    KEY_PROG1 = 148,
    KEY_PROG2 = 149,
    KEY_WWW = 150,
    KEY_MSDOS = 151,
    KEY_COFFEE = 152,
    KEY_SCREENLOCK = KEY_COFFEE,
    KEY_ROTATE_DISPLAY = 153,
    KEY_DIRECTION = KEY_ROTATE_DISPLAY,
    KEY_CYCLEWINDOWS = 154,
    KEY_MAIL = 155,
    KEY_BOOKMARKS = 156,
    KEY_COMPUTER = 157,
    KEY_BACK = 158,
    KEY_FORWARD = 159,
    KEY_CLOSECD = 160,
    KEY_EJECTCD = 161,
    KEY_EJECTCLOSECD = 162,
    KEY_NEXTSONG = 163,
    KEY_PLAYPAUSE = 164,
    KEY_PREVIOUSSONG = 165,
    KEY_STOPCD = 166,
    KEY_RECORD = 167,
    KEY_REWIND = 168,
    KEY_PHONE = 169,
    KEY_ISO = 170,
    KEY_CONFIG = 171,
    KEY_HOMEPAGE = 172,
    KEY_REFRESH = 173,
    KEY_EXIT = 174,
    KEY_MOVE = 175,
    KEY_EDIT = 176,
    KEY_SCROLLUP = 177,
    KEY_SCROLLDOWN = 178,
    KEY_KPLEFTPAREN = 179,
    KEY_KPRIGHTPAREN = 180,
    KEY_NEW = 181,
    KEY_REDO = 182,
    KEY_F13 = 183,
    KEY_F14 = 184,
    KEY_F15 = 185,
    KEY_F16 = 186,
    KEY_F17 = 187,
    KEY_F18 = 188,
    KEY_F19 = 189,
    KEY_F20 = 190,
    KEY_F21 = 191,
    KEY_F22 = 192,
    KEY_F23 = 193,
    KEY_F24 = 194,
    KEY_PLAYCD = 200,
    KEY_PAUSECD = 201,
    KEY_PROG3 = 202,
    KEY_PROG4 = 203,
    KEY_ALL_APPLICATIONS = 204,
    KEY_DASHBOARD = KEY_ALL_APPLICATIONS,
    KEY_SUSPEND = 205,
    KEY_CLOSE = 206,
    KEY_PLAY = 207,
    KEY_FASTFORWARD = 208,
    KEY_BASSBOOST = 209,
    KEY_PRINT = 210,
    KEY_HP = 211,
    KEY_CAMERA = 212,
    KEY_SOUND = 213,
    KEY_QUESTION = 214,
    KEY_EMAIL = 215,
    KEY_CHAT = 216,
    KEY_SEARCH = 217,
    KEY_CONNECT = 218,
    KEY_FINANCE = 219,
    KEY_SPORT = 220,
    KEY_SHOP = 221,
    KEY_ALTERASE = 222,
    KEY_CANCEL = 223,
    KEY_BRIGHTNESSDOWN = 224,
    KEY_BRIGHTNESSUP = 225,
    KEY_MEDIA = 226,
    KEY_SWITCHVIDEOMODE = 227,
    KEY_KBDILLUMTOGGLE = 228,
    KEY_KBDILLUMDOWN = 229,
    KEY_KBDILLUMUP = 230,
    KEY_SEND = 231,
    KEY_REPLY = 232,
    KEY_FORWARDMAIL = 233,
    KEY_SAVE = 234,
    KEY_DOCUMENTS = 235,
    KEY_BATTERY = 236,
    KEY_BLUETOOTH = 237,
    KEY_WLAN = 238,
    KEY_UWB = 239,
    KEY_UNKNOWN = 240,
    KEY_VIDEO_NEXT = 241,
    KEY_VIDEO_PREV = 242,
    KEY_BRIGHTNESS_CYCLE = 243,
    KEY_BRIGHTNESS_AUTO = 244,
    KEY_BRIGHTNESS_ZERO = KEY_BRIGHTNESS_AUTO,
    KEY_DISPLAY_OFF = 245,
    KEY_WWAN = 246,
    KEY_WIMAX = KEY_WWAN,
    KEY_RFKILL = 247,
    KEY_MICMUTE = 248,
    KEY_OK = 0x160,
    KEY_SELECT = 0x161,
    KEY_GOTO = 0x162,
    KEY_CLEAR = 0x163,
    KEY_POWER2 = 0x164,
    KEY_OPTION = 0x165,
    KEY_INFO = 0x166,
    KEY_TIME = 0x167,
    KEY_VENDOR = 0x168,
    KEY_ARCHIVE = 0x169,
    KEY_PROGRAM = 0x16a,
    KEY_CHANNEL = 0x16b,
    KEY_FAVORITES = 0x16c,
    KEY_EPG = 0x16d,
    KEY_PVR = 0x16e,
    KEY_MHP = 0x16f,
    KEY_LANGUAGE = 0x170,
    KEY_TITLE = 0x171,
    KEY_SUBTITLE = 0x172,
    KEY_ANGLE = 0x173,
    KEY_FULL_SCREEN = 0x174,
    KEY_ZOOM = KEY_FULL_SCREEN,
    KEY_MODE = 0x175,
    KEY_KEYBOARD = 0x176,
    KEY_ASPECT_RATIO = 0x177,
    KEY_SCREEN = KEY_ASPECT_RATIO,
    KEY_PC = 0x178,
    KEY_TV = 0x179,
    KEY_TV2 = 0x17a,
    KEY_VCR = 0x17b,
    KEY_VCR2 = 0x17c,
    KEY_SAT = 0x17d,
    KEY_SAT2 = 0x17e,
    KEY_CD = 0x17f,
    KEY_TAPE = 0x180,
    KEY_RADIO = 0x181,
    KEY_TUNER = 0x182,
    KEY_PLAYER = 0x183,
    KEY_TEXT = 0x184,
    KEY_DVD = 0x185,
    KEY_AUX = 0x186,
    KEY_MP3 = 0x187,
    KEY_AUDIO = 0x188,
    KEY_VIDEO = 0x189,
    KEY_DIRECTORY = 0x18a,
    KEY_LIST = 0x18b,
    KEY_MEMO = 0x18c,
    KEY_CALENDAR = 0x18d,
    KEY_RED = 0x18e,
    KEY_GREEN = 0x18f,
    KEY_YELLOW = 0x190,
    KEY_BLUE = 0x191,
    KEY_CHANNELUP = 0x192,
    KEY_CHANNELDOWN = 0x193,
    KEY_FIRST = 0x194,
    KEY_LAST = 0x195,
    KEY_AB = 0x196,
    KEY_NEXT = 0x197,
    KEY_RESTART = 0x198,
    KEY_SLOW = 0x199,
    KEY_SHUFFLE = 0x19a,
    KEY_BREAK = 0x19b,
    KEY_PREVIOUS = 0x19c,
    KEY_DIGITS = 0x19d,
    KEY_TEEN = 0x19e,
    KEY_TWEN = 0x19f,
    KEY_VIDEOPHONE = 0x1a0,
    KEY_GAMES = 0x1a1,
    KEY_ZOOMIN = 0x1a2,
    KEY_ZOOMOUT = 0x1a3,
    KEY_ZOOMRESET = 0x1a4,
    KEY_WORDPROCESSOR = 0x1a5,
    KEY_EDITOR = 0x1a6,
    KEY_SPREADSHEET = 0x1a7,
    KEY_GRAPHICSEDITOR = 0x1a8,
    KEY_PRESENTATION = 0x1a9,
    KEY_DATABASE = 0x1aa,
    KEY_NEWS = 0x1ab,
    KEY_VOICEMAIL = 0x1ac,
    KEY_ADDRESSBOOK = 0x1ad,
    KEY_MESSENGER = 0x1ae,
    KEY_DISPLAYTOGGLE = 0x1af,
    KEY_BRIGHTNESS_TOGGLE = KEY_DISPLAYTOGGLE,
    KEY_SPELLCHECK = 0x1b0,
    KEY_LOGOFF = 0x1b1,
    KEY_DOLLAR = 0x1b2,
    KEY_EURO = 0x1b3,
    KEY_FRAMEBACK = 0x1b4,
    KEY_FRAMEFORWARD = 0x1b5,
    KEY_CONTEXT_MENU = 0x1b6,
    KEY_MEDIA_REPEAT = 0x1b7,
    KEY_10CHANNELSUP = 0x1b8,
    KEY_10CHANNELSDOWN = 0x1b9,
    KEY_IMAGES = 0x1ba,
    KEY_NOTIFICATION_CENTER = 0x1bc,
    KEY_PICKUP_PHONE = 0x1bd,
    KEY_HANGUP_PHONE = 0x1be,
    KEY_LINK_PHONE = 0x1bf,
    KEY_DEL_EOL = 0x1c0,
    KEY_DEL_EOS = 0x1c1,
    KEY_INS_LINE = 0x1c2,
    KEY_DEL_LINE = 0x1c3,
    KEY_FN = 0x1d0,
    KEY_FN_ESC = 0x1d1,
    KEY_FN_F1 = 0x1d2,
    KEY_FN_F2 = 0x1d3,
    KEY_FN_F3 = 0x1d4,
    KEY_FN_F4 = 0x1d5,
    KEY_FN_F5 = 0x1d6,
    KEY_FN_F6 = 0x1d7,
    KEY_FN_F7 = 0x1d8,
    KEY_FN_F8 = 0x1d9,
    KEY_FN_F9 = 0x1da,
    KEY_FN_F10 = 0x1db,
    KEY_FN_F11 = 0x1dc,
    KEY_FN_F12 = 0x1dd,
    KEY_FN_1 = 0x1de,
    KEY_FN_2 = 0x1df,
    KEY_FN_D = 0x1e0,
    KEY_FN_E = 0x1e1,
    KEY_FN_F = 0x1e2,
    KEY_FN_S = 0x1e3,
    KEY_FN_B = 0x1e4,
    KEY_FN_RIGHT_SHIFT = 0x1e5,
    KEY_BRL_DOT1 = 0x1f1,
    KEY_BRL_DOT2 = 0x1f2,
    KEY_BRL_DOT3 = 0x1f3,
    KEY_BRL_DOT4 = 0x1f4,
    KEY_BRL_DOT5 = 0x1f5,
    KEY_BRL_DOT6 = 0x1f6,
    KEY_BRL_DOT7 = 0x1f7,
    KEY_BRL_DOT8 = 0x1f8,
    KEY_BRL_DOT9 = 0x1f9,
    KEY_BRL_DOT10 = 0x1fa,
    KEY_NUMERIC_0 = 0x200,
    KEY_NUMERIC_1 = 0x201,
    KEY_NUMERIC_2 = 0x202,
    KEY_NUMERIC_3 = 0x203,
    KEY_NUMERIC_4 = 0x204,
    KEY_NUMERIC_5 = 0x205,
    KEY_NUMERIC_6 = 0x206,
    KEY_NUMERIC_7 = 0x207,
    KEY_NUMERIC_8 = 0x208,
    KEY_NUMERIC_9 = 0x209,
    KEY_NUMERIC_STAR = 0x20a,
    KEY_NUMERIC_POUND = 0x20b,
    KEY_NUMERIC_A = 0x20c,
    KEY_NUMERIC_B = 0x20d,
    KEY_NUMERIC_C = 0x20e,
    KEY_NUMERIC_D = 0x20f,
    KEY_CAMERA_FOCUS = 0x210,
    KEY_WPS_BUTTON = 0x211,
    KEY_TOUCHPAD_TOGGLE = 0x212,
    KEY_TOUCHPAD_ON = 0x213,
    KEY_TOUCHPAD_OFF = 0x214,
    KEY_CAMERA_ZOOMIN = 0x215,
    KEY_CAMERA_ZOOMOUT = 0x216,
    KEY_CAMERA_UP = 0x217,
    KEY_CAMERA_DOWN = 0x218,
    KEY_CAMERA_LEFT = 0x219,
    KEY_CAMERA_RIGHT = 0x21a,
    KEY_ATTENDANT_ON = 0x21b,
    KEY_ATTENDANT_OFF = 0x21c,
    KEY_ATTENDANT_TOGGLE = 0x21d,
    KEY_LIGHTS_TOGGLE = 0x21e,
    KEY_ALS_TOGGLE = 0x230,
    KEY_ROTATE_LOCK_TOGGLE = 0x231,
    KEY_REFRESH_RATE_TOGGLE = 0x232,
    KEY_BUTTONCONFIG = 0x240,
    KEY_TASKMANAGER = 0x241,
    KEY_JOURNAL = 0x242,
    KEY_CONTROLPANEL = 0x243,
    KEY_APPSELECT = 0x244,
    KEY_SCREENSAVER = 0x245,
    KEY_VOICECOMMAND = 0x246,
    KEY_ASSISTANT = 0x247,
    KEY_KBD_LAYOUT_NEXT = 0x248,
    KEY_EMOJI_PICKER = 0x249,
    KEY_DICTATE = 0x24a,
    KEY_CAMERA_ACCESS_ENABLE = 0x24b,
    KEY_CAMERA_ACCESS_DISABLE = 0x24c,
    KEY_CAMERA_ACCESS_TOGGLE = 0x24d,
    KEY_ACCESSIBILITY = 0x24e,
    KEY_DO_NOT_DISTURB = 0x24f,
    KEY_BRIGHTNESS_MIN = 0x250,
    KEY_BRIGHTNESS_MAX = 0x251,
    KEY_KBDINPUTASSIST_PREV = 0x260,
    KEY_KBDINPUTASSIST_NEXT = 0x261,
    KEY_KBDINPUTASSIST_PREVGROUP = 0x262,
    KEY_KBDINPUTASSIST_NEXTGROUP = 0x263,
    KEY_KBDINPUTASSIST_ACCEPT = 0x264,
    KEY_KBDINPUTASSIST_CANCEL = 0x265,
    KEY_RIGHT_UP = 0x266,
    KEY_RIGHT_DOWN = 0x267,
    KEY_LEFT_UP = 0x268,
    KEY_LEFT_DOWN = 0x269,
    KEY_ROOT_MENU = 0x26a,
    KEY_MEDIA_TOP_MENU = 0x26b,
    KEY_NUMERIC_11 = 0x26c,
    KEY_NUMERIC_12 = 0x26d,
    KEY_AUDIO_DESC = 0x26e,
    KEY_3D_MODE = 0x26f,
    KEY_NEXT_FAVORITE = 0x270,
    KEY_STOP_RECORD = 0x271,
    KEY_PAUSE_RECORD = 0x272,
    KEY_VOD = 0x273,
    KEY_UNMUTE = 0x274,
    KEY_FASTREVERSE = 0x275,
    KEY_SLOWREVERSE = 0x276,
    KEY_DATA = 0x277,
    KEY_ONSCREEN_KEYBOARD = 0x278,
    KEY_PRIVACY_SCREEN_TOGGLE = 0x279,
    KEY_SELECTIVE_SCREENSHOT = 0x27a,
    KEY_NEXT_ELEMENT = 0x27b,
    KEY_PREVIOUS_ELEMENT = 0x27c,
    KEY_AUTOPILOT_ENGAGE_TOGGLE = 0x27d,
    KEY_MARK_WAYPOINT = 0x27e,
    KEY_SOS = 0x27f,
    KEY_NAV_CHART = 0x280,
    KEY_FISHING_CHART = 0x281,
    KEY_SINGLE_RANGE_RADAR = 0x282,
    KEY_DUAL_RANGE_RADAR = 0x283,
    KEY_RADAR_OVERLAY = 0x284,
    KEY_TRADITIONAL_SONAR = 0x285,
    KEY_CLEARVU_SONAR = 0x286,
    KEY_SIDEVU_SONAR = 0x287,
    KEY_NAV_INFO = 0x288,
    KEY_BRIGHTNESS_MENU = 0x289,
    KEY_MACRO1 = 0x290,
    KEY_MACRO2 = 0x291,
    KEY_MACRO3 = 0x292,
    KEY_MACRO4 = 0x293,
    KEY_MACRO5 = 0x294,
    KEY_MACRO6 = 0x295,
    KEY_MACRO7 = 0x296,
    KEY_MACRO8 = 0x297,
    KEY_MACRO9 = 0x298,
    KEY_MACRO10 = 0x299,
    KEY_MACRO11 = 0x29a,
    KEY_MACRO12 = 0x29b,
    KEY_MACRO13 = 0x29c,
    KEY_MACRO14 = 0x29d,
    KEY_MACRO15 = 0x29e,
    KEY_MACRO16 = 0x29f,
    KEY_MACRO17 = 0x2a0,
    KEY_MACRO18 = 0x2a1,
    KEY_MACRO19 = 0x2a2,
    KEY_MACRO20 = 0x2a3,
    KEY_MACRO21 = 0x2a4,
    KEY_MACRO22 = 0x2a5,
    KEY_MACRO23 = 0x2a6,
    KEY_MACRO24 = 0x2a7,
    KEY_MACRO25 = 0x2a8,
    KEY_MACRO26 = 0x2a9,
    KEY_MACRO27 = 0x2aa,
    KEY_MACRO28 = 0x2ab,
    KEY_MACRO29 = 0x2ac,
    KEY_MACRO30 = 0x2ad,
    KEY_MACRO_RECORD_START = 0x2b0,
    KEY_MACRO_RECORD_STOP = 0x2b1,
    KEY_MACRO_PRESET_CYCLE = 0x2b2,
    KEY_MACRO_PRESET1 = 0x2b3,
    KEY_MACRO_PRESET2 = 0x2b4,
    KEY_MACRO_PRESET3 = 0x2b5,
    KEY_KBD_LCD_MENU1 = 0x2b8,
    KEY_KBD_LCD_MENU2 = 0x2b9,
    KEY_KBD_LCD_MENU3 = 0x2ba,
    KEY_KBD_LCD_MENU4 = 0x2bb,
    KEY_KBD_LCD_MENU5 = 0x2bc,
    KEY_MIN_INTERESTING = KEY_MUTE,
    KEY_MAX = 0x2ff,
    KEY_CNT = (KEY_MAX + 1),
    
    
    // mouse buttons
    BTN_LEFT = 0x110,
    BTN_RIGHT = 0x111,
    BTN_MIDDLE = 0x112,
    BTN_SIDE = 0x113,
    BTN_EXTRA = 0x114,
    BTN_FORWARD = 0x115,
    BTN_BACK = 0x116,
    BTN_TASK = 0x117,
    //BTN_JOYSTICK = 0x118,
}